ARG GANTE_PUBLIC_PATH
ARG GANTE_PSQL_UNAME
ARG GANTE_PSQL_PASS

FROM node:20-alpine

WORKDIR /gante/

COPY ./.next/standalone ./
COPY ./public ./public
COPY ./.next/static ./.next/static

ENV GANTE_PUBLIC_PATH=$GANTE_PUBLIC_PATH
ENV GANTE_PSQL_UNAME=$GANTE_PSQL_UNAME
ENV GANTE_PSQL_PASS=$GANTE_PSQL_PASS

ENV PORT=8088

CMD [ "node", "./server.js"]
