ARG GANTE_PUBLIC_PATH
ARG GANTE_PSQL_UNAME
ARG GANTE_PSQL_PASS

FROM node:16.19.0

WORKDIR /gante/

COPY ./ ./

ENV GANTE_PUBLIC_PATH=$GANTE_PUBLIC_PATH
ENV GANTE_PSQL_UNAME=$GANTE_PSQL_UNAME
ENV GANTE_PSQL_PASS=$GANTE_PSQL_PASS

ENV PORT=3000

CMD [ "node", "./.next/standalone/server.js"]
