name: Node.js CI

on:
  push:
    branches: [ "master", "aliyun-dev", "test-workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
  build-image:
    runs-on: ubuntu-latest
    environment: production
    env:
      GANTE_PUBLIC_PATH: ${{secret.gante_public_path}}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      name: setup pnpm
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 16.19.0
        cache: 'pnpm'

    - uses: aliyun/setup-ossutil-environment@latest
      name: Setup aliyun ossutil
      with:
        access-key-id: ${{secrets.oss_access_key_id}}
        access-key-secret: ${{secrets.oss_access_secret}}
        endpoint: ${{secrets.oss_endpoint}}

    - name: install dependencies
      run: pnpm i --forzen-lockfile

    - name: build
      run: pnpm run build

    - name: Sync file to oss
      run: |
        ossutil sync .next/static oss://gantestatic/_next/static -f
        ossutil sync public oss://gantestatic -f
    - name: Login to docker
      uses: docker/login-action@v3
      with:
        username: ${{secret.DOCKER_USER}}
        password: ${{secret.DOCKER_PASS}}

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{secret.DOCKER_URL}}/liquanwei/gante:latest
        cache-from: type=registry
        cache-to: type=registry,mode=max
        build-args: |
          GANTE_PUBLIC_PATH=${{secret.GANTE_PUBLIC_PATH}}
          GANTE_PSQL_UNAME=${{secret.GANTE_PSQL_UNAME}}
          GANTE_PSQL_PASS=${{secret.GANTE_PSQL_PASS}}
