name: Node.js CI

on:
  push:
    branches: [ "master", "aliyun-dev", "test-workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: production
    env:
      GANTE_PUBLIC_PATH: ${{secrets.gante_public_path}}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      name: setup pnpm
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 18.12.0
        cache: 'pnpm'

    - uses: manyuanrong/setup-ossutil@v2.0
      name: Setup aliyun ossutil
      with:
        access-key-id: ${{secrets.OSS_ACCESS_KEY_ID}}
        access-key-secret: ${{secrets.SS_ACCESS_SECRET}}
        endpoint: ${{secrets.OSS_ENDPOINT}}

    - name: install dependencies
      run: pnpm i --frozen-lockfile

    - name: build
      run: pnpm run build

    - name: Sync file to oss
      run: |
        ossutil cp .next/static oss://gantestatic/_next/static -rf
        ossutil cp public oss://gantestatic -rf
    - name: Login to docker
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_URL}}/liquanwei/gante:latest
        cache-from: type=registry
        cache-to: type=registry,mode=max
        build-args: |
          GANTE_PUBLIC_PATH=${{secrets.GANTE_PUBLIC_PATH}}
          GANTE_PSQL_UNAME=${{secrets.GANTE_PSQL_UNAME}}
          GANTE_PSQL_PASS=${{secrets.GANTE_PSQL_PASS}}
